### ISSUE TITLE
LAN play gui not working when moved to second hdd

### ISSUE THREAD

**Issue by AdmiralPurple** [takashi1kun/lan-play-GUI#12]
**Describe the bug**
Lan play GUI works when folder is located on desktop but not when placed in second hdd. 

**To Reproduce**
1. Place lan play gui folder in hdd
2. Update lan play directory in settings 
3. DNS error

**Expected behavior**
DNS error and no cmd prompt pop up when located in second hdd. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version Windows 10 Pro 1803, Firefox 66.0.5 64 bit

**Additional context**
When the win-unpack folder is located on my desktop it works perfectly fine, when moved to D:/ (my second hdd) it no longer works, switch gets dns error.

**Comment by takashi1kun** [comment]
you have to reselect the network interface i guess.... lan play gui actually does not do that much, its just a slightly more convenient way to launch lan play
