### ISSUE TITLE
Cannot delete

### ISSUE THREAD

**Issue by Jatsotserah** [takashi1kun/lan-play-GUI#19]
**Describe the bug**
Once the files are deleted from the location and re-dowloaded, the GUI shows old directory in options. Green light does not appear to the servers anymore.

**To Reproduce**
1. Go to 'GUI'
2. Click on 'Settings'
3. See error

**Expected behavior**
Once deleted, it should have been gone.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Mozilla]
 - Version [e.g. Latest to Feb 26.]

**Additional context**
How to wipe the device without leftovers?

**Comment by takashi1kun** [comment]
Don't use the GUI right now, i am going to refactor it and do it again from scratch, this GUI brings me shame on how bullshitty i programmed it. 

TO wipe the device whitout leftovers you need to go to appdata and search for the GUI config files

**Comment by takashi1kun** [comment]
@Jatsotserah Good news, i aleardy started with the refactor this is how is going to look lan play GUI 2.0 :  
![image](https://user-images.githubusercontent.com/16158418/76160391-43aaa900-612a-11ea-9862-3c9864a85179.png)

**Comment by Jatsotserah** [comment]
> @Jatsotserah Good news, i aleardy started with the refactor this is how is going to look lan play GUI 2.0 :
> ![image](https://user-images.githubusercontent.com/16158418/76160391-43aaa900-612a-11ea-9862-3c9864a85179.png)

It is looking good.
