### ISSUE TITLE
If the Lan Play Location is not on the C\: drive it won't open

### ISSUE THREAD

**Issue by kapiteinvanhetschip** [takashi1kun/lan-play-GUI#23]
If the lan-play-win64 is not on the C\: drive it won't open. I have a separate HDD for my data so if I store it there it wont open. For example D:\User\Documents\Switch\lan-play-GUI open it from there with the lan-play-win64 in the same folder and added the location in lan play-Gui the command prompt won't open up.

But if I place the folder C:\lan-play-GUI and open it from there with the lan-play-win64 in the same folder and added the location in lan play-Gui it works as expected.

**Comment by Antik98** [comment]
I am running it on C:\ Without a problem, maybe your username has a space in it? Referring to  #22

**Comment by deadair3210** [comment]
I think they mean it won't launch if it's NOT on the C: drive

**Comment by kapiteinvanhetschip** [comment]
> I think they mean it won't launch if it's NOT on the C: drive

Exactly

**Comment by Antik98** [comment]
Yep did not read correctly, sorry

**Comment by takashi1kun** [comment]
@kapiteinvanhetschip i can't reproduce the issue in my system, it works fine in any drive, even having for example let's say the GUI on drive E and the lan-play-win64 binary in drive G or both on drive E or any combination, so it may be some weird behavior between a specific of your computer and the wanky code i wrote.
Anyway i am working in a version 2.0.0 made from scratch that would work much much better, i suggest waiting for the moment:
![image](https://user-images.githubusercontent.com/16158418/77936427-2ee9ad00-72b3-11ea-9a18-4e43ec5bc876.png)

**Comment by kapiteinvanhetschip** [comment]
Thanks for the response. I hope the next update fill fix it! Fingerscrossed :)
