### ISSUE TITLE
JavaScript Error 

### ISSUE THREAD

**Issue by Sirliamtron** [takashi1kun/lan-play-GUI#24]
GUI was working fine however I switched servers and it forced a reboot on my PC. Now whenever I try to open I recieve this error. Happens both when using original files and with fresh redownloaded ones. 

![image](https://user-images.githubusercontent.com/31524878/77347659-149e5500-6d30-11ea-8214-624b6a8ecc88.png)

After trying to run it it both the error and gui shows in task manager 

![image](https://user-images.githubusercontent.com/31524878/77347875-6ba42a00-6d30-11ea-91c6-97967ff8a888.png)

**Comment by takashi1kun** [comment]
100% sure this is a problem of the wanky shit tier code i wrote for the GUI, sorry i am currently working on version 2.0 and is nearly finished so i recommend for you to wait a bit until i release version 2.0 here is a preview:
![image](https://user-images.githubusercontent.com/16158418/77936809-b505f380-72b3-11ea-854e-7efc8c35db24.png)
