### ISSUE TITLE
After last Update - lan-play is not opening in cmd without error msg

### ISSUE THREAD

**Issue by strikeru97** [takashi1kun/lan-play-GUI#26]
**Describe the bug**
Lan-Gui does not start LAN-PLAY after last LAN-PLAY Update.

**To Reproduce**
1. Go to 'Main Windows'
2. Click on 'Connect on any server'
4. See error 'no error message only lan-gui is on but no cmd window for lan-play.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [1.30 of Lan-Gui]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by takashi1kun** [comment]
Try using a older version

**Comment by strikeru97** [comment]
Than lan play gui say new version available... You must update

Aitor Rosell Torralba <notifications@github.com> schrieb am So., 12. Apr.
2020, 21:48:

**Comment by takashi1kun** [comment]
I was meaning to use a older version of lan play, not of the gui, i am currently working on a new GUI made from scratch science the old one was a mess, use a older version of lan play until i release it okay?
