### ISSUE TITLE
No Interface, cmd does not open

### ISSUE THREAD

**Issue by pfckiko** [takashi1kun/lan-play-GUI#31]
**Describe the bug**
Few issues the first issue is that the Lan-play Cmd does not open when I click connect on the server. The second issue is that when I load interfaces it does not show my wired or wireless adapters. it only shows my VPN.

**To Reproduce**
Steps to reproduce the behavior of server not connecting:
1. Go to 'server list'
2. Click on 'any server you manually added'
3. Nothing comes up.

**To Reproduce**
Steps to reproduce the behavior not showing network adapters:
1. Go to 'settings'
2. Click on 'network adapters'
3.  Click on 'load interfaces.
4. No interfaces show up

**Expected behavior**
on the first part I though it opens the lan-play cmd and it connects you to the server you clicked on.
I thought it was going going to see all network adapters.

**Screenshots**
<a href="https://ibb.co/1MX31Z3"><img src="https://i.ibb.co/1MX31Z3/Capture.png" alt="Capture" border="0"></a>
<a href="https://ibb.co/WKTR57T"><img src="https://i.ibb.co/WKTR57T/Capture1.png" alt="Capture1" border="0"></a>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser any you want
 - Version latest

**Smartphone (please complete the following information):**
 - Device: note 10
 - OS: latest

**Comment by takashi1kun** [comment]
Had you tried to run it as administrator?

**Comment by pfckiko** [comment]
Yes.

**Comment by takashi1kun** [comment]
can you run the normal switch lan play binary with this property? --list-if, basically to get the interfaces on the gui i run the binary of SLP with the --list-if and that gets me the interfaces.

can you run it on a powershell or cmd to see if is a problem of SLP or of the GUI?

Probably it is going to be of the GUI, because when i did this i did some bullshit level filtering, to "try" to remove interfaces i thought were "useless", i am making a new version that does not include this behavior.

**Comment by demalmar** [comment]
I have the exact same issue. Clean Win10, everything running as admin, CMD not popping up when starting server.

**Comment by demalmar** [comment]
I don't know exactly how to apply the above written, what's the binary? you mean the file that runs the CMD or your program?

**Comment by pfckiko** [comment]
> I don't know exactly how to apply the above written, what's the binary? you mean the file that runs the CMD or your program?

Bud. All you have to do is grab the lan-play file and put it inside the folder where the lan-play-gui is located

**Comment by demalmar** [comment]
> > I don't know exactly how to apply the above written, what's the binary? you mean the file that runs the CMD or your program?
> 
> Bud. All you have to do is grab the lan-play file and put it inside the folder where the lan-play-gui is located

That's was set, and also selected in options.
Used to work in my windows before formatting.

**Comment by demalmar** [comment]
Wolved by downloading everything again and placing it in a new folder ¯\_(ツ)_/¯

**Comment by takashi1kun** [comment]
> Solved by downloading everything again and placing it in a new folder ¯_(ツ)_/¯

May be corruption issues, or weird folder structure issues then, glad you got it working

**Comment by yaseen420** [comment]
I had the exact issue. If you have any "spaces" in any of the folder names in the path, then it doesn't work. Just make sure none of the folders have any spaces in their names.
