### ISSUE TITLE
Lan Play CMD does not start when clicking "Connect to Server"

### ISSUE THREAD

**Issue by Michael-Shaw-Jr** [takashi1kun/lan-play-GUI#34]
On Windows 64 bit, when I click "Connect to Server" The button changes to "Disconnect from Server" but the CMD window never opens. I tried running as Administrator and that did not fix the issue. I also tried running Lan Play as Administrator and not Lan Play GUI. That didn't work either.

**Comment by boindil** [comment]
+1 same for me.

disabling UAC does "something". a cmd pops up, but closes immediately.

**Comment by takashi1kun** [comment]
But does it work?
Even if no cmd pops up, try to connect to it through your switch as if the cmd was there.
I don't remember as it was some time ago, but i think that for some reason i disable the cmd in the 1.3.0 version or something, but it should still be there, running in the background.

**Comment by pfckiko** [comment]
so once I put the file inside the folder it works. the only thing is you cannot redirect the location of the file.

**Comment by pfckiko** [comment]
> But does it work?
> Even if no cmd pops up, try to connect to it through your switch as if the cmd was there.
> I don't remember as it was some time ago, but i think that for some reason i disabled the cmd popping up in the 1.3.0 version or something, but slp should still be running there, running in the background.

no it did not

**Comment by takashi1kun** [comment]
@pfckiko  So if you put the binary of lan play in the same folder it works? then that is fine, in the next version the binaries will come bundled so this kind of problems do not happen.

**Comment by nwwj88** [comment]
I've put the lan-play in the same folder as lan play GUI, i add a server and click "Connect to Server", the button changes to "Disconnect from Server", but switch fails to connect. I tried to run lan-play only and manually key in the same server, it's able to connect.
