### ISSUE TITLE
package for Raspberry Pi not installing

### ISSUE THREAD

**Issue by jaycee79** [takashi1kun/lan-play-GUI#4]
The package you provide does not install on Raspbian stretch, it has a problem with compilation version armv7l instead of armhf, even by changing the dpkg configuration to allow armv7l it still gives dependancies errors.
Please tell me if you need logs or something to get things sorted out.

**Comment by jaycee79** [comment]
Seems like a compiling error with the electron tool : https://github.com/electron-userland/electron-builder/issues/1230

**Comment by jaycee79** [comment]
Sorry saw you closed the exact same issue for another user. dpkg does not work. Seems like an upstream error on the project, you can close the ticket then, but you should withdraw the Pi packet as it does not work, too bad. Thank you for your work !

**Comment by takashi1kun** [comment]
It does work on some models of raspberry pi.

**Comment by takashi1kun** [comment]
I literally tested on my own raspberry pi, it works on pi
