### ISSUE TITLE
raspberry error

### ISSUE THREAD

**Issue by impeeza** [takashi1kun/lan-play-GUI#49]
**Describe the bug**
Running the lan-play-GUI-raspberryPi-1.3.0.AppImage file on a Raspberry I get the "Invalid Instruction" error

**To Reproduce**
1. Install fresh 2019-04-08-raspbian-stretch.zip 
2. Setup Network
3. run sudo apt install libpcap0.8-dev libuv1-dev on pi
4. Download and copy lan-play raspberry client from https://github.com/RetroGamer74/RaspberryLanPlayClient
5. chmod 755 lan-play
6. download and copy lan-play-GUI-raspberryPi-1.3.0.AppImage to pi
7. chmod 755 lan-play-GUI-raspberryPi-1.3.0.AppImage 
8. run ./lan-play-GUI-raspberryPi-1.3.0.AppImage on pi desktop

**Expected behavior**
the gui should open.

**Screenshots**
No applicable

**Desktop (please complete the following information):**
 - OS: 2019-04-08-raspbian-stretch.zip 
 - Browser: chromium
 - Version 73.0.36

any additional step I miss?

**Comment by takashi1kun** [comment]
I no longer maintain this, i am very sorry, But if u want, u can run the gui without compiling or other stuff.
Clone this repo in a folder
cd to the repo
npm install
npm run start

**Comment by impeeza** [comment]
Thanks a lot, i will try, but as I am using a Raspberry Pi Zero W,  will be a lot of hand work,  is ARMv6 so.  

thanks for your effort, regards from Colombia.
