### ISSUE TITLE
Update servers list from lan-play.com

### ISSUE THREAD

**Issue by GreatWizard** [takashi1kun/lan-play-GUI#6]
Recently, I started to expose a `server.json` file on lan-play.com to be able to reuse an up-to-date servers list where you want.

The file format is a list of object like:
```json
{
  "ip": "switch.lan-play.com",
  "port": 11451,
  "flag": "fr",
  "platform": "switch"
}
```

Here is the link: http://lan-play.com/data/servers.json

**Comment by takashi1kun** [comment]
Added, new update would include it
