### ISSUE TITLE
能不能加个选项把cmd窗口隐藏？

### ISSUE THREAD

**Issue by snakwu** [takashi1kun/lan-play-GUI#9]
能不能加个选项把cmd窗口隐藏？  
EDIT:  
Translation by google translation:  
Can you add an option to hide the cmd window?

**Comment by takashi1kun** [comment]
No i cannot, i wish i can but is impossible on windows, on the other hand in linux is the opposite, is hiden and is impossible to show it. 
If it is not run detached and in a shell(cmd in this case) it refuses to work and electron does not allow to hide the cmd if you run it in shell and detached, sorry is out of my control.
